resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c6a35b9e8b8ab1fcee00a0e3279995d7f7cf97db9ce05c1d7515eafa850d77fb
  name: quay.io/kevindubois/quinoa-wind-turbine
