resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5eb3eb4e38b330131ca8d82a72a05ec6296a1b315ec285bb921d53db10d08792
  name: quay.io/kevindubois/quinoa-wind-turbine
