resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:6f8ca0b5743cb52f76c52557711c81c00d3809a463f64a6ceb933e703224854b
  name: quay.io/kevindubois/quinoa-wind-turbine
