resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:754376e908ab476afbd11ecf7a9cb2d9056347b7e62fd1dfcadcf6fd7c5281ba
  name: quay.io/kevindubois/quinoa-wind-turbine
