resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:db866d64516f79b1c71155109448d8c9521f35dc859c1731188780e7547644c7
  name: quay.io/kevindubois/quinoa-wind-turbine
