resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:5f6c3ae3a3c07f108af1cf005e2cb9993dfdf59f4682209a75e8634d8d3bcb84
  name: quay.io/kevindubois/quinoa-wind-turbine
