resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b98f3510d0f07ebb5583c69bd8090b374ffbb4fdd80dd9aa3d03ee97fbed434e
  name: quay.io/kevindubois/quinoa-wind-turbine
