resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:297514ef95047b6ba5b24dc8996e78a8ecc051feae6f43fb8402359ebe447101
  name: quay.io/kevindubois/quinoa-wind-turbine
