resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2a8ff942c4b2110c5f5ca566ae91e18880b2a44e299af896d595890ceafb16fc
  name: quay.io/kevindubois/quinoa-wind-turbine
