resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:1e6db4ad5d5ff946cf7d6fe4ab2f83d4e649752c94543188bf1723081eb5ac06
  name: quay.io/kevindubois/quinoa-wind-turbine
