resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e8c050a0d8acf14cde1c98635030c16b6f5753f890d5701ce3b86435ce418206
  name: quay.io/kevindubois/quinoa-wind-turbine
