resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e3c02a40be0e5f41bf4b0975c08ffffa20bcfce3a84184466cae7e74bc9429dd
  name: quay.io/kevindubois/quinoa-wind-turbine
