resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b409eae9fbe78fcb4e3abcd980d61a027cbb21b592c48ad8cfa6ac2abb289afe
  name: quay.io/kevindubois/quinoa-wind-turbine
