resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:26a64d639b63ab76132cbc246a208dd565be605b14fc8c5f7e536cbd367a63c8
  name: quay.io/kevindubois/quinoa-wind-turbine
