resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:7bad154bf8d9d2b6d2a216cca3188f477b23858f74afdb198611ffb19d6121b3
  name: quay.io/kevindubois/quinoa-wind-turbine
