resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:e162f664b47e66256be15db121e099c1755f4370116085240aa2ef856d8dc30c
  name: quay.io/kevindubois/quinoa-wind-turbine
