resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3cdf02e2e630e1e80b67e9851f5729a350cde912c5746bafdb957df95640a701
  name: quay.io/kevindubois/quinoa-wind-turbine
