resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dc5524917e8bb5c86f92e16b86e7423cf81c3d162b04aaea8b25222e13c4a515
  name: quay.io/kevindubois/quinoa-wind-turbine
