resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b5134d1eb9fd37258bfc5e042709b936169d87664d712f58fcfbfbae427e7702
  name: quay.io/kevindubois/quinoa-wind-turbine
