resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:299d602ec374f8f3da97030bc8a7ffc426298d95b8a4994b38cf1e9192f44e14
  name: quay.io/kevindubois/quinoa-wind-turbine
