resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:349a000736212c5c145081367210cb8ff247e2d6cd62636b62bae9325f020eda
  name: quay.io/kevindubois/quinoa-wind-turbine
