resources:
- deployment.yaml
- service.yaml
- route.yaml
- servicemonitor.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c6749870977b9986a14f0f7633cb397007bfdd75d4a93e7e9bc9f1b919fc19cc
  name: quay.io/kevindubois/quinoa-wind-turbine
