resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:46d7a714b3099972dc233e85ba840d9d376c30ddc22442eea3195941c04666a6
  name: quay.io/kevindubois/quinoa-wind-turbine
