apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: wind-turbine-monitor
  name: wind-turbine-monitor
  namespace: demo
spec:
  endpoints:
  - interval: 30s
    port: '8080-tcp'
    scheme: http
  selector:
    matchLabels:
      app: quinoa-wind-turbine